package com;

/**
 * @author : jignesh.sheth Date: 11/29/12 Time: 4:49 PM
 */
public enum PatternsName {
  SINGLETON, FACTORY, ABSTRACT_FACTORY, BUILDER, PROTOTYPE,
  ADAPTER, COMPOSITE, PROXY, FLYWEIGHT, FACADE, BRIDGE, DECORATOR,
  TEMPLATE, MEDIATOR, CHAIN_OF_RESPONSIBILITY, OBSERVER, STRATEGY,
  COMMAND, STATE, VISITOR, ITERATOR, MEMENTO
}
